name: open_dir
description: Plugin for opening native directory on desktop platforms
repository: https://github.com/huynguyennovem/open_dir/tree/main/open_dir
issue_tracker: https://github.com/huynguyennovem/open_dir/issues
version: 0.0.1+1

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      macos:
        default_package: open_dir_macos

dependencies:
  flutter:
    sdk: flutter
  open_dir_platform_interface: ^0.0.1
  open_dir_macos: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.0.2   # This is required for testing
