name: open_dir_linux
description: Linux implementation of the open_dir plugin
repository: https://github.com/huynguyennovem/open_dir/tree/main/open_dir_linux
issue_tracker: https://github.com/huynguyennovem/open_dir/issues
version: 0.0.2+1

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: open_dir
    platforms:
      linux:
        dartPluginClass: OpenDirLinux
        pluginClass: OpenDirLinuxPlugin

dependencies:
  flutter:
    sdk: flutter
  open_dir_platform_interface: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0