name: open_dir_windows
description: Windows implementation of the open_dir plugin
repository: https://github.com/huynguyennovem/open_dir/tree/main/open_dir_windows
issue_tracker: https://github.com/huynguyennovem/open_dir/issues
version: 0.0.1

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: open_dir
    platforms:
      windows:
        dartPluginClass: OpenDirWindows
        pluginClass: OpenDirWindowsPluginCApi

dependencies:
  flutter:
    sdk: flutter
  open_dir_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
